baseurl = "http://wuwei.io/"
languageCode = "en-us"
title = "Wuwei Lin"
theme = "hugo-classic"
googleAnalytics = "UA-90229954-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
canonifyURLs = false

[permalinks]
    post = "/post/:year/:month/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    footer = "©2018 Wuwei Lin | Theme by [Hugo-Classic](https://github.com/vinx13/hugo-classic)" 
    custom_css = ["css/theme-override.css"]

[author]
    name = "Wuwei Lin"


[taxonomies]
  tag = "tags"
